/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Website pages. Each page is built from reusable, orderable blocks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL identifier for this page, e.g. "home", "about". Used by the frontend to look up page content.
   */
  pageSlug: string;
  /**
   * Drag blocks to reorder sections. Add any block type to build the page.
   */
  content?: (HeroBlock | MentalHealthBlock | GalleryBlock | OfferingsBlock | CTABlock | FAQBlock)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  eyebrowLabel?: string | null;
  headline: string;
  description?: string | null;
  primaryButtonText?: string | null;
  secondaryButtonText?: string | null;
  badge1Title?: string | null;
  badge1Description?: string | null;
  badge2Title?: string | null;
  badge2Description?: string | null;
  founderImage?: (number | null) | Media;
  founderCaption?: string | null;
  founderTitle?: string | null;
  starRatingLabel?: string | null;
  zeroJudgmentLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MentalHealthBlock".
 */
export interface MentalHealthBlock {
  sectionLabel?: string | null;
  headline?: string | null;
  description?: string | null;
  /**
   * Cards shown in the grid. Each card maps to a mental health / life situation.
   */
  categories?:
    | {
        iconType: 'brain-circuit' | 'heart' | 'eye-off' | 'activity' | 'milestone';
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  ctaCardEyebrow?: string | null;
  ctaCardTitle?: string | null;
  ctaCardDescription?: string | null;
  ctaCardButtonText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mental-health';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  sectionLabel?: string | null;
  headline?: string | null;
  description?: string | null;
  /**
   * Before and after image pairs. Drag to reorder.
   */
  items?:
    | {
        beforeImage: number | Media;
        afterImage: number | Media;
        label: string;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  dignityNote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OfferingsBlock".
 */
export interface OfferingsBlock {
  sectionLabel?: string | null;
  headline?: string | null;
  description?: string | null;
  /**
   * The service cards shown in the grid. Drag to reorder.
   */
  services?:
    | {
        serviceSlug: 'gentle-reset' | 'maintenance' | 'deep-transition' | 'neurodivergent' | 'custom-care';
        iconType: 'coffee' | 'calendar' | 'layers' | 'heart-handshake';
        title: string;
        subtitle?: string | null;
        description: string;
        features?:
          | {
              feature: string;
              id?: string | null;
            }[]
          | null;
        vibe?: string | null;
        id?: string | null;
      }[]
    | null;
  customCareTitle?: string | null;
  customCareDescription?: string | null;
  customCareButtonText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'offerings';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock".
 */
export interface CTABlock {
  sectionLabel?: string | null;
  headline?: string | null;
  headlineHighlight?: string | null;
  description?: string | null;
  buttonText?: string | null;
  buttonSubtext?: string | null;
  reassurances?:
    | {
        iconType: 'shield-check' | 'clock' | 'heart' | 'sparkles';
        label: string;
        id?: string | null;
      }[]
    | null;
  quote?: string | null;
  quoteAttribution?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  sectionLabel?: string | null;
  headline?: string | null;
  description?: string | null;
  /**
   * Questions and answers shown in the accordion. Drag to reorder.
   */
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  pageSlug?: T;
  content?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        'mental-health'?: T | MentalHealthBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        offerings?: T | OfferingsBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrowLabel?: T;
  headline?: T;
  description?: T;
  primaryButtonText?: T;
  secondaryButtonText?: T;
  badge1Title?: T;
  badge1Description?: T;
  badge2Title?: T;
  badge2Description?: T;
  founderImage?: T;
  founderCaption?: T;
  founderTitle?: T;
  starRatingLabel?: T;
  zeroJudgmentLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MentalHealthBlock_select".
 */
export interface MentalHealthBlockSelect<T extends boolean = true> {
  sectionLabel?: T;
  headline?: T;
  description?: T;
  categories?:
    | T
    | {
        iconType?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  ctaCardEyebrow?: T;
  ctaCardTitle?: T;
  ctaCardDescription?: T;
  ctaCardButtonText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  sectionLabel?: T;
  headline?: T;
  description?: T;
  items?:
    | T
    | {
        beforeImage?: T;
        afterImage?: T;
        label?: T;
        caption?: T;
        id?: T;
      };
  dignityNote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OfferingsBlock_select".
 */
export interface OfferingsBlockSelect<T extends boolean = true> {
  sectionLabel?: T;
  headline?: T;
  description?: T;
  services?:
    | T
    | {
        serviceSlug?: T;
        iconType?: T;
        title?: T;
        subtitle?: T;
        description?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        vibe?: T;
        id?: T;
      };
  customCareTitle?: T;
  customCareDescription?: T;
  customCareButtonText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock_select".
 */
export interface CTABlockSelect<T extends boolean = true> {
  sectionLabel?: T;
  headline?: T;
  headlineHighlight?: T;
  description?: T;
  buttonText?: T;
  buttonSubtext?: T;
  reassurances?:
    | T
    | {
        iconType?: T;
        label?: T;
        id?: T;
      };
  quote?: T;
  quoteAttribution?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  sectionLabel?: T;
  headline?: T;
  description?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global brand info, contact details, and social links used across the entire site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName: string;
  tagline?: string | null;
  phone?: string | null;
  phoneTel?: string | null;
  email?: string | null;
  address?: string | null;
  instagramHandle?: string | null;
  instagramUrl?: string | null;
  insuranceText?: string | null;
  localityBadgeText?: string | null;
  footerDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  tagline?: T;
  phone?: T;
  phoneTel?: T;
  email?: T;
  address?: T;
  instagramHandle?: T;
  instagramUrl?: T;
  insuranceText?: T;
  localityBadgeText?: T;
  footerDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}